apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  host: "host.docker.internal"  # หรือ localhost ถ้าใช้ Docker Desktop
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"
