apiVersion: batch/v1
kind: Job
metadata:
  name: job-publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        image: batch-job:latest
        imagePullPolicy: Never
        command: ["./job-publisher"]
        env:
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "postgres"
        - name: REDIS_ADDR
          value: "redis-service:6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: OnFailure
