apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: users-batch
spec:
  pollingInterval: 30
  maxReplicaCount: 5
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  triggers:
    - type: postgresql
      authenticationRef:
        name: pgconn
      metadata:
        query: "SELECT COUNT(1) FROM users WHERE batch_status IN ('pending','failed')"
        # targetQueryValue: "10000000"   # backlog 10M ต่อ 1 replica
        targetQueryValue: "20000"
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: batch-worker:latest
          imagePullPolicy: Never
          env:
          - name: PG_DSN
            value: "postgres://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable"
          - name: CLAIM_SIZE
            value: "20000"
          - name: WORKERS
            value: "8"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"  
              cpu: "500m"
