apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-worker
spec:
  replicas: 2  # เริ่มด้วย 2 pods
  selector:
    matchLabels:
      app: batch-worker
  template:
    metadata:
      labels:
        app: batch-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: worker
        image: batch-job:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "postgres"
        - name: REDIS_ADDR
          value: "redis-service:6379"
        - name: CONCURRENT_WORKERS
          value: "4"
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: batch-worker-service
spec:
  selector:
    app: batch-worker
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
